Revert "Add WireGuard for v5.5 - 2020-03-30"
This reverts commit af2ea5dbfdc06d07182b39cfb738a7ceb9194eb2.

Doesn't build with 5.5.14, did with 5.5.13.  Let's wait for an official
patch from the WireGuard team considering both Zen and Liquorix haven't
had a successful release with WireGuard yet.

Errors from build log:

In file included from drivers/net/wireguard/main.c:9:
drivers/net/wireguard/queueing.h: In function ‘wg_reset_packet’:
drivers/net/wireguard/queueing.h:103:2: error: implicit declaration of function ‘skb_reset_tc’; did you mean ‘nf_reset_ct’? [-Werror=implicit-function-declaration]
  103 |  skb_reset_tc(skb);
      |  ^~~~~~~~~~~~
      |  nf_reset_ct
In file included from drivers/net/wireguard/noise.c:10:
drivers/net/wireguard/queueing.h: In function ‘wg_reset_packet’:
drivers/net/wireguard/queueing.h:103:2: error: implicit declaration of function ‘skb_reset_tc’; did you mean ‘nf_reset_ct’? [-Werror=implicit-function-declaration]
  103 |  skb_reset_tc(skb);
      |  ^~~~~~~~~~~~
      |  nf_reset_ct
  CC [M]  drivers/net/eql.o
cc1: some warnings being treated as errors
In file included from drivers/net/wireguard/device.c:6:
drivers/net/wireguard/queueing.h: In function ‘wg_reset_packet’:
drivers/net/wireguard/queueing.h:103:2: error: implicit declaration of function ‘skb_reset_tc’; did you mean ‘nf_reset_ct’? [-Werror=implicit-function-declaration]
  103 |  skb_reset_tc(skb);
      |  ^~~~~~~~~~~~
      |  nf_reset_ct
make[3]: *** [scripts/Makefile.build:266: drivers/net/wireguard/main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC [M]  drivers/net/ifb.o
In file included from drivers/net/wireguard/peer.c:8:
drivers/net/wireguard/queueing.h: In function ‘wg_reset_packet’:
drivers/net/wireguard/queueing.h:103:2: error: implicit declaration of function ‘skb_reset_tc’; did you mean ‘nf_reset_ct’? [-Werror=implicit-function-declaration]
  103 |  skb_reset_tc(skb);
      |  ^~~~~~~~~~~~
      |  nf_reset_ct
  CC [M]  drivers/net/macsec.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:266: drivers/net/wireguard/peer.o] Error 1
  CC [M]  drivers/net/wireless/ath/ath5k/caps.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:266: drivers/net/wireguard/device.o] Error 1
  CC [M]  drivers/net/wireless/ath/ath6kl/debug.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:266: drivers/net/wireguard/noise.o] Error 1
make[2]: *** [scripts/Makefile.build:503: drivers/net/wireguard] Error 2
make[2]: *** Waiting for unfinished jobs....